import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { createManualApInvoice } from "@/app/procurement-actions";
import { companyShortName } from "@/lib/company";
import { FlashMessage, PageHeader } from "@/components/procurement-ui";

export default async function NewApInvoicePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams; const [companies, suppliers, items] = await Promise.all([prisma.company.findMany({ where: { status: "ACTIVE" }, orderBy: { code: "asc" } }), prisma.supplier.findMany({ where: { status: "ACTIVE" }, include: { companies: true }, orderBy: { code: "asc" } }), prisma.item.findMany({ where: { status: "ACTIVE" }, include: { company: true }, orderBy: [{ companyId: "asc" }, { code: "asc" }] })]);
  return <><PageHeader eyebrow="財務帳款" title="新增人工應付" backHref="/ap-invoices" description="適用於費用、固定資產與 Ragic 舊資料；不會建立採購或庫存紀錄。" /><FlashMessage error={error} />
    <form action={createManualApInvoice} className="panel space-y-6 p-6"><fieldset className="form-section"><legend>發票資訊</legend><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      <label className="field-label">公司 *<select className="field-input" name="companyId" required><option value="">請選擇</option>{companies.map((company) => <option key={company.id} value={company.id}>{companyShortName(company)}</option>)}</select></label><label className="field-label">供應商 *<select className="field-input" name="supplierId" required><option value="">請選擇</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.code} {supplier.name}</option>)}</select></label>
      <label className="field-label">來源類型 *<select className="field-input" name="sourceType" required><option value="MANUAL_EXPENSE">人工費用</option><option value="FIXED_ASSET">固定資產</option><option value="LEGACY_IMPORT">Ragic 舊資料</option></select></label><label className="field-label">廠商發票號碼<input className="field-input" name="supplierInvoiceNumber" /></label><label className="field-label">開立日期 *<input className="field-input" name="invoiceDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label className="field-label">應付日期<input className="field-input" name="dueDate" type="date" /></label><label className="field-label">Ragic 舊單號<input className="field-input" name="legacyCode" /></label>
    </div></fieldset><fieldset className="form-section"><legend>明細</legend><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      <label className="field-label xl:col-span-2">品項（費用可不選）<select className="field-input" name="itemId"><option value="">非品項費用</option>{items.map((item) => <option key={item.id} value={item.id}>{companyShortName(item.company)}｜{item.code}｜{item.name}</option>)}</select></label><label className="field-label">說明 *<input className="field-input" name="description" required /></label><label className="field-label">數量 *<input className="field-input" name="quantity" type="number" min="0.001" step="0.001" defaultValue="1" required /></label><label className="field-label">單位<input className="field-input" name="unit" /></label><label className="field-label">單價 *<input className="field-input" name="unitPrice" type="number" min="0" step="0.0001" required /></label><label className="field-label">稅率 %<input className="field-input" name="taxRate" type="number" min="0" step="0.01" defaultValue="0" /></label><label className="field-label">運費<input className="field-input" name="freightAmount" type="number" min="0" step="0.01" defaultValue="0" /></label>
    </div></fieldset><label className="field-label">備註<textarea className="field-textarea" name="note" /></label><div className="action-row"><button className="primary-button" type="submit">建立應付發票</button><Link className="secondary-button inline-flex items-center" href="/ap-invoices">取消</Link></div></form></>;
}
