import { companyShortName } from "@/lib/company";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { addGoodsReceiptLot, createApInvoiceFromGoodsReceipt, postGoodsReceipt, updateGoodsReceiptLineQuantities } from "@/app/procurement-actions";
import { DetailField, DetailGrid, DetailSection, EmptyRow, FlashMessage, PageHeader, StatusPill } from "@/components/procurement-ui";
import { formatDate, formatMoney, formatQuantity, goodsReceiptStatusLabel } from "@/lib/procurement";

export default async function GoodsReceiptDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const { error, success } = await searchParams; const receiptId = Number(id); if (!Number.isInteger(receiptId)) notFound();
  const receipt = await prisma.goodsReceipt.findUnique({
    where: { id: receiptId },
    include: { company: true, supplier: true, warehouse: true, purchaseOrder: true, lines: { include: { item: true, lots: { include: { stockMovement: true } }, apInvoiceSources: { include: { apInvoiceLine: { include: { apInvoice: true } } } } }, orderBy: { lineNo: "asc" } } },
  });
  if (!receipt) notFound();
  const invoiceLinks = [...new Map(receipt.lines.flatMap((line) => line.apInvoiceSources.map((source) => source.apInvoiceLine.apInvoice)).map((invoice) => [invoice.id, invoice])).values()];
  return <><PageHeader eyebrow="採購／庫存" title={receipt.number} backHref="/goods-receipts" /><FlashMessage error={error} success={success} />
    <DetailSection title="進貨資訊" tone="blue"><DetailGrid><DetailField label="公司">{companyShortName(receipt.company)}</DetailField><DetailField label="狀態"><StatusPill>{goodsReceiptStatusLabel[receipt.status]}</StatusPill></DetailField><DetailField label="來源採購單"><Link className="table-link" href={`/purchase-orders/${receipt.purchaseOrderId}`}>{receipt.purchaseOrder.number}</Link></DetailField><DetailField label="供應商">{receipt.supplierNameSnapshot}</DetailField><DetailField label="收貨日期">{formatDate(receipt.receiptDate)}</DetailField><DetailField label="倉庫">{receipt.warehouse.code} {receipt.warehouse.name}</DetailField></DetailGrid></DetailSection>
    <DetailSection title="進貨明細與批次" tone="amber"><div className="space-y-5">{receipt.lines.map((line) => <div key={line.id} className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex flex-wrap justify-between gap-2"><div><strong>{line.lineNo}. {line.itemCodeSnapshot} {line.itemNameSnapshot}</strong><p className="text-xs text-slate-500">{line.itemSpecSnapshot}｜實收 {formatQuantity(line.receivedQuantity)}／合格 {formatQuantity(line.acceptedQuantity)}／拒收 {formatQuantity(line.rejectedQuantity)} {line.unitSnapshot}｜成本 {line.unitCost ? formatMoney(line.unitCost) : "—"}</p></div><span className="text-xs font-bold text-slate-500">批號管理：{line.item.trackLot ? "是" : "否"}／效期管理：{line.item.trackExpiry ? "是" : "否"}</span></div>
      {receipt.status === "DRAFT" ? <form action={updateGoodsReceiptLineQuantities.bind(null, receipt.id, line.id)} className="inline-form mb-3"><label className="field-label">實收數量 *<input className="field-input" name="receivedQuantity" type="number" min="0.001" step="0.001" defaultValue={Number(line.receivedQuantity)} required /></label><label className="field-label">合格數量 *<input className="field-input" name="acceptedQuantity" type="number" min="0.001" step="0.001" defaultValue={Number(line.acceptedQuantity)} required /></label><label className="field-label">拒收數量 *<input className="field-input" name="rejectedQuantity" type="number" min="0" step="0.001" defaultValue={Number(line.rejectedQuantity)} required /></label><button className="secondary-button" type="submit">更新驗收數量</button></form> : null}
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>批號</th><th>效期</th><th>數量</th><th>入庫異動</th></tr></thead><tbody>{line.lots.map((lot) => <tr key={lot.id}><td>{lot.lotNumber ?? "不管理"}</td><td>{formatDate(lot.expiryDate)}</td><td>{formatQuantity(lot.quantity)}</td><td>{lot.stockMovement ? "已建立" : "尚未入庫"}</td></tr>)}{line.lots.length === 0 ? <EmptyRow colSpan={4} message="請新增批號／效期資料" /> : null}</tbody></table></div>
      {receipt.status === "DRAFT" && (line.item.trackLot || line.item.trackExpiry) ? <form action={addGoodsReceiptLot.bind(null, receipt.id, line.id)} className="inline-form mt-3"><label className="field-label">批號{line.item.trackLot ? " *" : ""}<input className="field-input" name="lotNumber" required={line.item.trackLot} /></label><label className="field-label">效期{line.item.trackExpiry ? " *" : ""}<input className="field-input" name="expiryDate" type="date" required={line.item.trackExpiry} /></label><label className="field-label">數量 *<input className="field-input" name="quantity" type="number" min="0.001" step="0.001" required /></label><button className="secondary-button" type="submit">新增批次</button></form> : null}
    </div>)}{receipt.lines.length === 0 ? <p className="text-sm text-slate-500">目前沒有進貨明細</p> : null}</div></DetailSection>
    <DetailSection title="流程操作"><div className="action-row">{receipt.status === "DRAFT" ? <form action={postGoodsReceipt.bind(null, receipt.id)}><button className="primary-button" type="submit">完成入庫</button></form> : null}
      {receipt.status === "RECEIVED" && invoiceLinks.length === 0 ? <form action={createApInvoiceFromGoodsReceipt.bind(null, receipt.id)} className="inline-form"><label className="field-label">廠商發票號碼<input className="field-input" name="supplierInvoiceNumber" /></label><label className="field-label">開立日期 *<input className="field-input" name="invoiceDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label className="field-label">應付日期<input className="field-input" name="dueDate" type="date" /></label><label className="field-label">備註<input className="field-input" name="note" /></label><button className="primary-button" type="submit">建立應付發票</button></form> : null}
      {invoiceLinks.map((invoice) => <Link key={invoice.id} className="secondary-button inline-flex items-center" href={`/ap-invoices/${invoice.id}`}>查看應付 {invoice.number}</Link>)}</div></DetailSection>
    <DetailSection title="系統資訊"><DetailGrid><DetailField label="建立時間">{receipt.createdAt.toLocaleString("zh-TW")}</DetailField><DetailField label="入庫時間">{receipt.postedAt?.toLocaleString("zh-TW")}</DetailField><DetailField label="備註">{receipt.note}</DetailField></DetailGrid></DetailSection>
  </>;
}
