import { companyShortName } from "@/lib/company";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { createReceiptForInvoice, postArInvoice } from "@/app/sales-actions";
import { DetailField, DetailGrid, DetailSection, EmptyRow, FlashMessage, PageHeader, StatusPill } from "@/components/procurement-ui";
import { arInvoiceStatusLabel, formatDate, formatMoney, formatQuantity } from "@/lib/sales";

export default async function ArInvoiceDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const { error, success } = await searchParams;
  const invoice = await prisma.arInvoice.findUnique({ where: { id: Number(id) }, include: { company: true, customer: true, salesDelivery: { include: { salesOrder: true } }, lines: { orderBy: { lineNo: "asc" } }, allocations: { include: { receipt: true }, orderBy: { allocatedAt: "asc" } } } });
  if (!invoice) notFound();
  const today = new Date().toISOString().slice(0, 10);
  return <><PageHeader eyebrow="財務帳款" title={`應收發票 ${invoice.number}`} backHref="/ar-invoices" description="金額依實際出庫明細建立，收款以獨立單據與沖帳紀錄保存。" /><FlashMessage error={error} success={success} />
    <DetailSection title="發票資訊" tone="amber"><DetailGrid><DetailField label="狀態"><StatusPill>{arInvoiceStatusLabel[invoice.status]}</StatusPill></DetailField><DetailField label="發票日期">{formatDate(invoice.invoiceDate)}</DetailField><DetailField label="到期日">{formatDate(invoice.dueDate)}</DetailField><DetailField label="銷售公司">{companyShortName(invoice.company)}</DetailField><DetailField label="客戶">{invoice.customerCodeSnapshot} {invoice.customerNameSnapshot}</DetailField><DetailField label="來源銷貨"><Link className="table-link" href={`/sales-deliveries/${invoice.salesDeliveryId}`}>{invoice.salesDelivery.number}</Link></DetailField><DetailField label="來源訂單"><Link className="table-link" href={`/sales-orders/${invoice.salesDelivery.salesOrderId}`}>{invoice.salesDelivery.salesOrder.number}</Link></DetailField><DetailField label="統一發票">{invoice.governmentInvoiceIssued ? invoice.governmentInvoiceNumber : "尚未開立"}</DetailField><DetailField label="帳單地址">{invoice.billingAddressSnapshot ?? "—"}</DetailField></DetailGrid></DetailSection>
    <DetailSection title="應收明細" tone="amber"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>項次</th><th>品號</th><th>品名／規格</th><th>數量</th><th>單價</th><th>稅率</th><th>金額</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id}><td>{line.lineNo}</td><td>{line.itemCodeSnapshot}</td><td>{line.descriptionSnapshot}{line.itemSpecSnapshot ? ` · ${line.itemSpecSnapshot}` : ""}</td><td>{formatQuantity(line.quantity)} {line.unitSnapshot}</td><td>{formatMoney(line.unitPrice, invoice.currency)}</td><td>{formatQuantity(line.taxRate)}%</td><td>{formatMoney(line.totalAmount, invoice.currency)}</td></tr>)}{invoice.lines.length === 0 ? <EmptyRow colSpan={7} /> : null}</tbody></table></div><div className="mt-5 grid justify-end gap-1 text-right"><span>未稅：{formatMoney(invoice.netAmount, invoice.currency)}</span><span>稅額：{formatMoney(invoice.taxAmount, invoice.currency)}</span><strong className="text-lg">總額：{formatMoney(invoice.totalAmount, invoice.currency)}</strong><strong className="text-rose-700">未收：{formatMoney(invoice.remainingBalance, invoice.currency)}</strong></div>{invoice.status === "DRAFT" ? <form action={postArInvoice.bind(null, invoice.id)} className="mt-5 border-t border-slate-100 pt-5"><button className="primary-button" type="submit">立帳</button></form> : null}</DetailSection>
    {["POSTED", "PARTIALLY_RECEIVED"].includes(invoice.status) ? <DetailSection title="新增收款" tone="teal"><form action={createReceiptForInvoice.bind(null, invoice.id)} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="field-label">收款日期 *<input className="field-input" name="receiptDate" type="date" defaultValue={today} required /></label><label className="field-label">收款方式 *<select className="field-input" name="paymentMethod" required><option value="匯款">匯款</option><option value="現金">現金</option><option value="支票">支票</option><option value="其他">其他</option></select></label><label className="field-label">金額 *<input className="field-input" name="amount" type="number" min="0.01" max={Number(invoice.remainingBalance)} step="0.01" defaultValue={Number(invoice.remainingBalance)} required /></label><label className="field-label">備註<input className="field-input" name="note" /></label><div><button className="primary-button" type="submit">收款並沖帳</button></div></form></DetailSection> : null}
    <DetailSection title="收款紀錄" tone="teal"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>收款單</th><th>日期</th><th>方式</th><th>沖帳金額</th><th>狀態</th></tr></thead><tbody>{invoice.allocations.map((allocation) => <tr key={allocation.id}><td><Link className="table-link" href={`/receipts/${allocation.receiptId}`}>{allocation.receipt.number}</Link></td><td>{formatDate(allocation.receipt.receiptDate)}</td><td>{allocation.receipt.paymentMethod}</td><td>{formatMoney(allocation.amount, invoice.currency)}</td><td>{allocation.receipt.status}</td></tr>)}{invoice.allocations.length === 0 ? <EmptyRow colSpan={5} /> : null}</tbody></table></div></DetailSection>
  </>;
}
