import { companyShortName } from "@/lib/company";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { allocateDeliveryLot, createArInvoiceFromDelivery, postSalesDelivery } from "@/app/sales-actions";
import { DetailField, DetailGrid, DetailSection, EmptyRow, FlashMessage, PageHeader, StatusPill } from "@/components/procurement-ui";
import { formatDate, formatMoney, formatQuantity, salesDeliveryStatusLabel } from "@/lib/sales";

export default async function SalesDeliveryDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const { error, success } = await searchParams;
  const delivery = await prisma.salesDelivery.findUnique({ where: { id: Number(id) }, include: { company: true, customer: true, salesOrder: true, warehouse: true, arInvoice: true, lines: { include: { lots: { include: { inventoryLot: true } } }, orderBy: { lineNo: "asc" } } } });
  if (!delivery) notFound();
  const lots = await prisma.inventoryLot.findMany({ where: { warehouseId: delivery.warehouseId, status: "AVAILABLE", quantity: { gt: 0 }, itemId: { in: delivery.lines.map((line) => line.itemId) } }, include: { item: true }, orderBy: [{ expiryDate: "asc" }, { lotNumber: "asc" }] });
  const today = new Date().toISOString().slice(0, 10);
  const total = delivery.lines.reduce((sum, line) => sum + Number(line.totalAmount), 0);
  return <><PageHeader eyebrow="銷售管理" title={`銷貨單 ${delivery.number}`} backHref="/sales-deliveries" description="批號分配總量必須等於銷貨數量；正式出庫以單一交易扣庫存。" /><FlashMessage error={error} success={success} />
    <DetailSection title="出貨資訊" tone="violet"><DetailGrid><DetailField label="狀態"><StatusPill>{salesDeliveryStatusLabel[delivery.status]}</StatusPill></DetailField><DetailField label="來源訂單"><Link className="table-link" href={`/sales-orders/${delivery.salesOrderId}`}>{delivery.salesOrder.number}</Link></DetailField><DetailField label="銷貨日期">{formatDate(delivery.deliveryDate)}</DetailField><DetailField label="銷售公司">{companyShortName(delivery.company)}</DetailField><DetailField label="客戶">{delivery.customerCodeSnapshot} {delivery.customerNameSnapshot}</DetailField><DetailField label="出庫倉庫">{delivery.warehouse.code} {delivery.warehouse.name}</DetailField><DetailField label="收件人">{delivery.recipientNameSnapshot ?? "—"} {delivery.recipientPhoneSnapshot ?? ""}</DetailField><DetailField label="送貨地址">{delivery.shippingPostalSnapshot ?? ""} {delivery.shippingAddressSnapshot}</DetailField><DetailField label="出庫執行時間">{delivery.postedAt ? delivery.postedAt.toLocaleString("zh-TW") : "—"}</DetailField></DetailGrid></DetailSection>
    <DetailSection title="銷貨項目與批號" tone="violet"><div className="space-y-6">{delivery.lines.map((line) => { const allocated = line.lots.reduce((sum, lot) => sum + Number(lot.quantity), 0); const options = lots.filter((lot) => lot.itemId === line.itemId); return <article key={line.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{line.itemCodeSnapshot} {line.itemNameSnapshot}</strong><p className="text-sm text-slate-500">{line.itemSpecSnapshot ?? "無規格"} · 銷貨 {formatQuantity(line.deliveredQuantity)} {line.unitSnapshot} · 已配批 {formatQuantity(allocated)}</p></div><strong>{formatMoney(line.totalAmount, delivery.salesOrder.currency)}</strong></div><div className="mt-3 data-table-wrap"><table className="data-table"><thead><tr><th>批號</th><th>效期</th><th>本次分配</th><th>目前庫存</th></tr></thead><tbody>{line.lots.map((entry) => <tr key={entry.id}><td>{entry.inventoryLot.lotNumber ?? "不管理"}</td><td>{formatDate(entry.inventoryLot.expiryDate)}</td><td>{formatQuantity(entry.quantity)}</td><td>{formatQuantity(entry.inventoryLot.quantity)}</td></tr>)}{line.lots.length === 0 ? <EmptyRow colSpan={4} message="尚未分配批號" /> : null}</tbody></table></div>{delivery.status === "PENDING_ISSUE" ? <form action={allocateDeliveryLot.bind(null, delivery.id, line.id)} className="mt-3 grid gap-3 md:grid-cols-[2fr_1fr_auto]"><label className="field-label">可用批號<select className="field-input" name="inventoryLotId" required><option value="">請選擇</option>{options.map((lot) => <option key={lot.id} value={lot.id}>{lot.lotNumber ?? "不管理批號"}｜效期 {formatDate(lot.expiryDate)}｜可用 {formatQuantity(lot.quantity)}</option>)}</select></label><label className="field-label">分配數量<input className="field-input" name="quantity" type="number" min="0.001" step="0.001" required /></label><button className="secondary-button self-end" type="submit">儲存分配</button></form> : null}</article>; })}</div><div className="mt-5 flex justify-end text-lg font-extrabold">銷貨金額：{formatMoney(total, delivery.salesOrder.currency)}</div>{delivery.status === "PENDING_ISSUE" ? <form action={postSalesDelivery.bind(null, delivery.id)} className="mt-5 border-t border-slate-100 pt-5"><button className="primary-button" type="submit">完成出庫</button></form> : null}</DetailSection>
    {delivery.status === "ISSUED" && !delivery.arInvoice ? <DetailSection title="建立應收發票" tone="amber"><form action={createArInvoiceFromDelivery.bind(null, delivery.id)} className="grid gap-4 md:grid-cols-2"><label className="field-label">發票日期 *<input className="field-input" name="invoiceDate" type="date" defaultValue={today} required /></label><label className="field-label">到期日<input className="field-input" name="dueDate" type="date" /></label><label className="field-label">統一發票號碼<input className="field-input" name="governmentInvoiceNumber" /></label><label className="field-label">備註<input className="field-input" name="note" /></label><div><button className="primary-button" type="submit">建立應收發票</button></div></form></DetailSection> : null}
    {delivery.arInvoice ? <DetailSection title="應收發票" tone="amber"><Link className="table-link" href={`/ar-invoices/${delivery.arInvoice.id}`}>{delivery.arInvoice.number}</Link></DetailSection> : null}
  </>;
}
