import { companyShortName } from "@/lib/company";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { addSalesOrderLine, confirmSalesOrder, createSalesDelivery } from "@/app/sales-actions";
import { DetailField, DetailGrid, DetailSection, EmptyRow, FlashMessage, PageHeader, StatusPill } from "@/components/procurement-ui";
import { formatDate, formatMoney, formatQuantity, salesDeliveryStatusLabel, salesOrderStatusLabel } from "@/lib/sales";

export default async function SalesOrderDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const { error, success } = await searchParams;
  const order = await prisma.salesOrder.findUnique({
    where: { id: Number(id) },
    include: {
      company: true, customer: true,
      lines: { include: { item: { include: { company: true } }, deliverySources: { where: { salesDeliveryLine: { salesDelivery: { status: { not: "CANCELLED" } } } } } }, orderBy: { lineNo: "asc" } },
      deliveries: { orderBy: { deliveryDate: "desc" } },
    },
  });
  if (!order) notFound();
  const [prices, warehouses] = await Promise.all([
    prisma.priceListItem.findMany({ where: { priceListId: order.customer.priceListId, item: { status: "ACTIVE" } }, include: { item: { include: { company: true } } }, orderBy: { item: { code: "asc" } } }),
    prisma.warehouse.findMany({ where: { status: "ACTIVE" }, orderBy: { code: "asc" } }),
  ]);
  const today = new Date().toISOString().slice(0, 10);
  return <><PageHeader eyebrow="銷售管理" title={`銷售訂單 ${order.number}`} backHref="/sales-orders" description="銷售公司由客戶歸屬決定；明細保留各品項產品公司。" /><FlashMessage error={error} success={success} />
    <DetailSection title="訂單資訊" tone="blue"><DetailGrid><DetailField label="狀態"><StatusPill>{salesOrderStatusLabel[order.status]}</StatusPill></DetailField><DetailField label="訂單日期">{formatDate(order.orderDate)}</DetailField><DetailField label="預計出貨">{formatDate(order.expectedShipDate)}</DetailField><DetailField label="銷售公司">{companyShortName(order.company)}</DetailField><DetailField label="客戶">{order.customerCodeSnapshot} {order.customerNameSnapshot}</DetailField><DetailField label="價格表">{order.priceListCodeSnapshot} {order.priceListNameSnapshot}</DetailField><DetailField label="收件人">{order.recipientNameSnapshot ?? "—"} {order.recipientPhoneSnapshot ?? ""}</DetailField><DetailField label="送貨地址">{order.shippingPostalSnapshot ?? ""} {order.shippingAddressSnapshot}</DetailField><DetailField label="付款條件">{order.paymentTermsSnapshot ?? "—"}</DetailField></DetailGrid></DetailSection>
    <DetailSection title="訂單項目" tone="blue"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>項次</th><th>產品公司／品號</th><th>品名／規格</th><th>數量</th><th>已出庫</th><th>已建立銷貨</th><th>單價</th><th>金額</th></tr></thead><tbody>{order.lines.map((line) => { const committed = line.deliverySources.reduce((sum, source) => sum + Number(source.quantity), 0); return <tr key={line.id}><td>{line.lineNo}</td><td>{companyShortName(line.item.company)}／{line.itemCodeSnapshot}</td><td>{line.itemNameSnapshot}{line.itemSpecSnapshot ? ` · ${line.itemSpecSnapshot}` : ""}</td><td>{formatQuantity(line.orderedQuantity)} {line.unitSnapshot}</td><td>{formatQuantity(line.deliveredQuantity)}</td><td>{formatQuantity(committed)}</td><td>{formatMoney(line.unitPrice, order.currency)}</td><td>{formatMoney(line.totalAmount, order.currency)}</td></tr>; })}{order.lines.length === 0 ? <EmptyRow colSpan={8} /> : null}</tbody></table></div>
      <div className="mt-5 flex justify-end text-lg font-extrabold">訂單總額：{formatMoney(order.totalAmount, order.currency)}</div></DetailSection>
    {order.status === "DRAFT" ? <DetailSection title="加入價格表品項"><form action={addSalesOrderLine.bind(null, order.id)} className="grid gap-4 md:grid-cols-[2fr_1fr_2fr_auto]"><label className="field-label">品項 *<select className="field-input" name="itemId" required><option value="">請選擇</option>{prices.filter((price) => !order.lines.some((line) => line.itemId === price.itemId)).map((price) => <option key={price.id} value={price.itemId}>{price.item.code} {price.item.name}｜{companyShortName(price.item.company)}｜{formatMoney(price.unitPrice, order.currency)}</option>)}</select></label><label className="field-label">數量 *<input className="field-input" name="quantity" type="number" min="0.001" step="0.001" required /></label><label className="field-label">備註<input className="field-input" name="note" /></label><button className="primary-button self-end" type="submit">加入</button></form>
      {order.lines.length > 0 ? <form action={confirmSalesOrder.bind(null, order.id)} className="mt-5 border-t border-slate-100 pt-5"><button className="primary-button" type="submit">確認訂單</button></form> : null}</DetailSection> : null}
    {["CONFIRMED", "PARTIALLY_DELIVERED"].includes(order.status) ? <DetailSection title="建立本次銷貨單" tone="violet"><form action={createSalesDelivery.bind(null, order.id)} className="space-y-5"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>品號</th><th>品名</th><th>訂購</th><th>已建立銷貨</th><th>本次銷貨</th></tr></thead><tbody>{order.lines.map((line) => { const committed = line.deliverySources.reduce((sum, source) => sum + Number(source.quantity), 0); const outstanding = Number(line.orderedQuantity) - Number(line.cancelledQuantity) - committed; return <tr key={line.id}><td>{line.itemCodeSnapshot}</td><td>{line.itemNameSnapshot}</td><td>{formatQuantity(line.orderedQuantity)}</td><td>{formatQuantity(committed)}</td><td><input className="field-input !mt-0 w-32" name={`quantity_${line.id}`} type="number" min="0" max={outstanding} step="0.001" defaultValue={outstanding > 0 ? outstanding : 0} disabled={outstanding <= 0} /></td></tr>; })}</tbody></table></div><div className="grid gap-4 md:grid-cols-3"><label className="field-label">出庫倉庫 *<select className="field-input" name="warehouseId" required>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.code} {warehouse.name}</option>)}</select></label><label className="field-label">銷貨日期 *<input className="field-input" name="deliveryDate" type="date" defaultValue={today} required /></label><label className="field-label">備註<input className="field-input" name="note" /></label></div><button className="primary-button" type="submit">建立銷貨單</button></form></DetailSection> : null}
    <DetailSection title="銷貨紀錄" tone="violet"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>銷貨單</th><th>日期</th><th>狀態</th></tr></thead><tbody>{order.deliveries.map((delivery) => <tr key={delivery.id}><td><Link className="table-link" href={`/sales-deliveries/${delivery.id}`}>{delivery.number}</Link></td><td>{formatDate(delivery.deliveryDate)}</td><td>{salesDeliveryStatusLabel[delivery.status]}</td></tr>)}{order.deliveries.length === 0 ? <EmptyRow colSpan={3} /> : null}</tbody></table></div></DetailSection>
  </>;
}
