import { companyShortName } from "@/lib/company";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { DetailField, DetailGrid, DetailSection, EmptyRow, FlashMessage, PageHeader, StatusPill } from "@/components/procurement-ui";
import { formatDate, formatMoney, paymentStatusLabel } from "@/lib/procurement";

export default async function PaymentDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const { error, success } = await searchParams; const paymentId = Number(id); if (!Number.isInteger(paymentId)) notFound(); const payment = await prisma.payment.findUnique({ where: { id: paymentId }, include: { company: true, supplier: true, allocations: { include: { apInvoice: true } } } }); if (!payment) notFound();
  return <><PageHeader eyebrow="財務帳款" title={payment.number} backHref="/payments" /><FlashMessage error={error} success={success} /><DetailSection title="付款資訊" tone="blue"><DetailGrid><DetailField label="公司">{companyShortName(payment.company)}</DetailField><DetailField label="供應商">{payment.supplier.name}</DetailField><DetailField label="付款日期">{formatDate(payment.paymentDate)}</DetailField><DetailField label="方式">{payment.paymentMethod}</DetailField><DetailField label="金額">{formatMoney(payment.totalAmount, payment.currency)}</DetailField><DetailField label="狀態"><StatusPill>{paymentStatusLabel[payment.status]}</StatusPill></DetailField></DetailGrid></DetailSection><DetailSection title="沖帳明細" tone="amber"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>應付單號</th><th>供應商發票</th><th>沖帳金額</th></tr></thead><tbody>{payment.allocations.map((allocation) => <tr key={allocation.id}><td><Link className="table-link" href={`/ap-invoices/${allocation.apInvoiceId}`}>{allocation.apInvoice.number}</Link></td><td>{allocation.apInvoice.supplierInvoiceNumber ?? "—"}</td><td>{formatMoney(allocation.amount, payment.currency)}</td></tr>)}{payment.allocations.length === 0 ? <EmptyRow colSpan={3} /> : null}</tbody></table></div></DetailSection><DetailSection title="系統資訊"><DetailGrid><DetailField label="建立時間">{payment.createdAt.toLocaleString("zh-TW")}</DetailField><DetailField label="確認時間">{payment.confirmedAt?.toLocaleString("zh-TW")}</DetailField><DetailField label="備註">{payment.note}</DetailField></DetailGrid></DetailSection></>;
}
