import { companyShortName } from "@/lib/company";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { createPaymentForInvoice, postApInvoice } from "@/app/procurement-actions";
import { DetailField, DetailGrid, DetailSection, EmptyRow, FlashMessage, PageHeader, StatusPill } from "@/components/procurement-ui";
import { apInvoiceStatusLabel, formatDate, formatMoney, formatQuantity } from "@/lib/procurement";

export default async function ApInvoiceDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const { error, success } = await searchParams; const invoiceId = Number(id); if (!Number.isInteger(invoiceId)) notFound();
  const invoice = await prisma.apInvoice.findUnique({ where: { id: invoiceId }, include: { company: true, supplier: true, lines: { include: { sources: { include: { goodsReceiptLine: { include: { goodsReceipt: true } }, purchaseOrderLine: { include: { purchaseOrder: true } } } } }, orderBy: { lineNo: "asc" } }, allocations: { include: { payment: true }, orderBy: { allocatedAt: "asc" } } } });
  if (!invoice) notFound();
  return <><PageHeader eyebrow="財務帳款" title={invoice.number} backHref="/ap-invoices" /><FlashMessage error={error} success={success} />
    <DetailSection title="發票資訊" tone="violet"><DetailGrid><DetailField label="公司">{companyShortName(invoice.company)}</DetailField><DetailField label="狀態"><StatusPill>{apInvoiceStatusLabel[invoice.status]}</StatusPill></DetailField><DetailField label="供應商">{invoice.supplierNameSnapshot}</DetailField><DetailField label="廠商發票號碼">{invoice.supplierInvoiceNumber}</DetailField><DetailField label="開立日期">{formatDate(invoice.invoiceDate)}</DetailField><DetailField label="應付日期">{formatDate(invoice.dueDate)}</DetailField><DetailField label="來源">{invoice.sourceType}</DetailField><DetailField label="總金額">{formatMoney(invoice.totalAmount, invoice.currency)}</DetailField><DetailField label="未付餘額">{formatMoney(invoice.remainingBalance, invoice.currency)}</DetailField></DetailGrid></DetailSection>
    <DetailSection title="發票明細" tone="amber"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>項次</th><th>品號／說明</th><th>數量</th><th>單價</th><th>未稅</th><th>稅額</th><th>來源</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id}><td>{line.lineNo}</td><td>{line.itemCodeSnapshot ? `${line.itemCodeSnapshot} ` : ""}{line.descriptionSnapshot}</td><td>{formatQuantity(line.quantity)} {line.unitSnapshot}</td><td>{formatMoney(line.unitPrice, invoice.currency)}</td><td>{formatMoney(line.netAmount, invoice.currency)}</td><td>{formatMoney(line.taxAmount, invoice.currency)}</td><td>{line.sources.map((source) => source.goodsReceiptLine ? <Link key={source.id} className="table-link mr-2" href={`/goods-receipts/${source.goodsReceiptLine.goodsReceiptId}`}>{source.goodsReceiptLine.goodsReceipt.number}</Link> : source.purchaseOrderLine ? <Link key={source.id} className="table-link mr-2" href={`/purchase-orders/${source.purchaseOrderLine.purchaseOrderId}`}>{source.purchaseOrderLine.purchaseOrder.number}</Link> : null)}</td></tr>)}{invoice.lines.length === 0 ? <EmptyRow colSpan={7} /> : null}</tbody></table></div></DetailSection>
    <DetailSection title="付款與沖帳" tone="blue"><div className="data-table-wrap mb-5"><table className="data-table"><thead><tr><th>付款單號</th><th>付款日期</th><th>沖帳金額</th></tr></thead><tbody>{invoice.allocations.map((allocation) => <tr key={allocation.id}><td><Link className="table-link" href={`/payments/${allocation.paymentId}`}>{allocation.payment.number}</Link></td><td>{formatDate(allocation.payment.paymentDate)}</td><td>{formatMoney(allocation.amount, invoice.currency)}</td></tr>)}{invoice.allocations.length === 0 ? <EmptyRow colSpan={3} /> : null}</tbody></table></div>
      {invoice.status === "DRAFT" || invoice.status === "PENDING_MATCH" ? <form action={postApInvoice.bind(null, invoice.id)}><button className="primary-button" type="submit">確認立帳</button></form> : null}
      {["POSTED", "PARTIALLY_PAID"].includes(invoice.status) ? <form action={createPaymentForInvoice.bind(null, invoice.id)} className="inline-form"><label className="field-label">付款日期 *<input className="field-input" name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label className="field-label">付款方式 *<select className="field-input" name="paymentMethod" required><option value="銀行轉帳">銀行轉帳</option><option value="現金">現金</option><option value="支票">支票</option></select></label><label className="field-label">付款金額 *<input className="field-input" name="amount" type="number" min="0.01" step="0.01" max={invoice.remainingBalance.toString()} defaultValue={invoice.remainingBalance.toString()} required /></label><label className="field-label">備註<input className="field-input" name="note" /></label><button className="primary-button" type="submit">付款並沖帳</button></form> : null}
    </DetailSection><DetailSection title="系統資訊"><DetailGrid><DetailField label="建立時間">{invoice.createdAt.toLocaleString("zh-TW")}</DetailField><DetailField label="立帳時間">{invoice.postedAt?.toLocaleString("zh-TW")}</DetailField><DetailField label="Ragic 舊單號">{invoice.legacyCode}</DetailField><DetailField label="備註">{invoice.note}</DetailField></DetailGrid></DetailSection>
  </>;
}
